<?php
//'配置项'=>'配置值'
	return array(
		'what_are_you_doing'	   =>	'当你看见这个的时候，我认为你是在浪费时间',
		'any_data_empty'		   =>	'必填数据不能为空',
		'no_purview'			   =>	'没有操作权限',
		'add_agents_success'	   =>	'成功添加代理商信息',
		'agent_exist'              =>  '已经有此代理商信息',
		'agent_area_exist'         =>  '已经有这个区域的代理商了',
		'add_delete_agent'	       =>	'请先恢复此代理商再添加',
		'add_agent_failed'	       =>	'添加代理商信息失败',
		'change_agent_success'	   =>	'成功修改代理商信息',
		'change_agent_name_failed' =>	'无法修改代理商名称,已经有这个代理商了',
		'change_agent_belongself'	=>  '所属代理商错误，请重新选择所属代理商',
		'change_agent_failed'	   =>	'修改代理商失败',
		'delete_agent_have_child'	   =>	'选择的组织机构存在下级组织机构，不能删除',
		'delete_agent_success'	   =>	'成功删除组织机构信息',
		'delete_agent_failed'	   =>	'删除组织机构信息失败',
		'verification_code_error'	=>	'验证码错误',
		'login_success'		=>	'登陆成功',
		'logout_success'	=>	'退出成功',
		'login_failed'		=>	'登陆失败(用户名/密码错误)',
		'no_have_this_username'		=>	'没有该用户，或者该用户已经失效',
		'add_role_success'		=>	'成功添加角色',
		'add_role_failed'		=>	'添加角色失败',
		'modify_role_success'		=>	'成功修改角色',
		'modify_role_failed'		=>	'修改角色失败',
		'delete_role_success'		=>	'成功删除角色',
		'delete_role_failed'		=>	'删除角色失败',
		'old_password_error'		=>	'旧密码错误',
		'new_password_not_same'		=>	'两次输入的新密码不一致',
		'change_password_success'   =>	'成功修改密码',
		'initial_password'   =>	'123456',
		'add_user_success'		=>	'成功添加用户',
		'user_name_same'		=>	'登录账号重复',
		'add_user_failed'		=>	'添加用户失败',
		'modify_user_success'		=>	'成功修改用户',
		'modify_user_failed'		=>	'修改用户失败',
		'delete_user_success'		=>	'成功删除用户',
		'delete_user_failed'		=>	'删除用户失败',
		'reset_password_success'		=>	'成功重置用户密码',
		'reset_password_failed'		=>	'已经是初始密码了，不需要重置',
		'modify_user_state_success'		=>	'成功修改用户状态',
		'modify_user_state_failed'		=>	'修改用户状态失败',
	);
?>