-- Script was generated by Devart dbForge Studio Express for MySQL, Version 6.0.265.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2014/5/23 10:59:49
-- Server version: 5.5.33
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(1, '北京');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(2, '上海');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(3, '黑龙江');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(4, '吉林');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(5, '辽宁');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(6, '天津');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(7, '安徽');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(8, '江苏');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(9, '浙江');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(10, '陕西');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(11, '湖北');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(12, '广东');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(13, '湖南');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(14, '甘肃');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(15, '四川');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(16, '山东');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(17, '福建');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(18, '河南');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(19, '重庆');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(20, '云南');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(21, '河北');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(22, '江西');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(23, '山西');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(24, '贵州');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(25, '广西');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(26, '内蒙古');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(27, '宁夏');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(28, '青海');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(29, '新疆');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(30, '海南');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(31, '西藏');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(32, '香港');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(33, '澳门');
INSERT INTO jnbizs.bi_province(prov_id, prov_name) VALUES
(34, '台湾');
